api_platform:
    title: 'Dabba REST API'
    description: 'A Symfony API to manage dabba consigne mobile app.'
    version: '0.1.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
#        api_keys:
#            apiKey:
#                name: Authorization
#                type: header
    oauth:
        enabled: true
        clientId: '%app.api.client_id%'
        clientSecret: '%app.api.client_secret%'
        type: 'oauth2'
        flow: 'password'
        tokenUrl: '/api/accessToken'
        authorizationUrl: '/api/accessToken'
        scopes: []
    formats:
        json:
            mime_types: [ 'application/json' ]
        html:
            mime_types: [ 'text/html' ]
    defaults:
        pagination_enabled: false
    exception_to_status:
        App\Exception\BadRequest: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        App\Exception\NotEnoughCredit: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        App\Exception\NotEnoughStock: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        App\Exception\NotFound: 404