# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.transactional_mail_sender: '%env(TRANSACTIONAL_MAIL_SENDER)%'
    app.path.restaurant_images: /uploads/images/restaurant
    app.path.cms_images: /uploads/images/cms
    app.api.client_id: '%env(API_CLIENT_ID)%'
    app.api.client_secret: '%env(API_CLIENT_SECRET)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Service/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    app.service.place:
        class: App\Service\Place
        public: true
        arguments:
            - '@csa_guzzle.client.google_maps'
            - '@jms_serializer'
            - '%env(GMAP_API_KEY)%'
    League\OAuth2\Server\AuthorizationServer:
        arguments:
            $clientRepository: '@App\Infrastructure\oAuth2Server\Bridge\ClientRepository'
            $accessTokenRepository: '@App\Infrastructure\oAuth2Server\Bridge\AccessTokenRepository'
            $scopeRepository: '@App\Infrastructure\oAuth2Server\Bridge\ScopeRepository'
            $privateKey: '%env(OAUTH2_PRIVATE_KEY)%'
            $encryptionKey: '%env(OAUTH2_ENCRYPTION_KEY)%'
    League\OAuth2\Server\Grant\PasswordGrant:
        arguments:
            $userRepository: '@App\Infrastructure\oAuth2Server\Bridge\UserRepository'
            $refreshTokenRepository: '@App\Infrastructure\oAuth2Server\Bridge\RefreshTokenRepository'
    League\OAuth2\Server\Grant\RefreshTokenGrant:
        arguments:
            $refreshTokenRepository: '@App\Infrastructure\oAuth2Server\Bridge\RefreshTokenRepository'
    App\MyResourceServer:
        arguments:
            $accessTokenRepository: '@App\Infrastructure\oAuth2Server\Bridge\AccessTokenRepository'
            $publicKey: '%env(OAUTH2_PUBLIC_KEY)%'